{{- if (eq (include "eric-data-document-database-pg.operator-enabled" .) "true") }}
{{- if eq (include "eric-data-document-database-pg.isOpMigrationRequired" .) "true" -}}
{{- $helmHooks := dict -}}
{{- $_ := set $helmHooks "helm.sh/hook" "pre-upgrade,pre-install" -}}
{{- $_ := set $helmHooks "helm.sh/hook-delete-policy" "before-hook-creation" -}}
{{- $_ := set $helmHooks "helm.sh/hook-weight" "-5" -}}
{{- $commonAnn := fromYaml (include "eric-data-document-database-pg.annotations" .) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "eric-data-document-database-pg.name" . }}-op-patch-hook
  labels: {{- include "eric-data-document-database-pg.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-data-document-database-pg.mergeAnnotations" (dict "location" .Template.Name "sources" (list $helmHooks $commonAnn)) | trim | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - watch
  # delete is required only for 'patronictl remove'
  - delete
  - deletecollection
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  verbs:
  - get
  - patch
  - update
  # the following three privileges are necessary only when using endpoints
  - create
  - list
  - watch
  # delete is required only for for 'patronictl remove'
  - delete
  - deletecollection
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - patch
  - delete
  - deletecollection
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - list
  - get
  - create
  - update
  - patch
  - delete
  - deletecollection
- apiGroups:
  - "apps"
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - update
  - patch
  - delete
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
  - delete
  - deletecollection
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - get
  - list
  - create
  - delete
  - deletecollection
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - deletecollection
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - create
  - patch
  - update
  - delete

- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - roles
  - rolebindings
# not specify resourceName because this role can not anticipate what roles and rolebindings to patch. The controller should have such specific permission.
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
  - delete
  - deletecollection

- apiGroups:
  - "networking.k8s.io"
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - create
  - patch
  - update
  - delete
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - create
  - patch
  - update
  - watch
  - delete
  - deletecollection
- apiGroups:
  - siptls.sec.ericsson.com
  resources:
  - internalcertificates
  - internalusercas
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - list
- apiGroups:
  - "docdb.data.ericsson.com"
  resources:
  - postgresqls
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
  - delete

# The following rules is for Openshift
- apiGroups:
  - ""
  resources:
  - endpoints/restricted
  verbs:
  - get
  - list
  - create
  - patch
  - update
  - delete
  - deletecollection
{{- end }}
{{- end }}
