# Default values for eric-pm-bulk-reporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#global:
#  fsGroup:
#    # 'manual' to enforce a specific value (this has the highest precedence)
#    manual:
#    # 'namespace' to use the value defined for the namespace set by the cluster admin (second highest precedence)
#    namespace:
#  pullSecret:
#  registry:
#    imagePullPolicy: IfNotPresent
#    url: armdocker.rnd.ericsson.se
    ## Secret must be manually created in the namespace.
    # deprecated, it will be removed
#    repoPath:
#    pullSecret:
#  security:
#    tls:
#      enabled: true
#      trustedInternalRootCa:
#        secret: eric-sec-sip-tls-trusted-root-cert
#    policyBinding:
#      create: true
#    policyReferenceMap: {}
#  timezone: UTC
#  nodeSelector: {}
#  hooklauncher:
#    executor: service
#    executorCharts: []
#  podSecurityContext:
#    supplementalGroups: []
#  securityPolicy:
#    rolekind: ""  # possible values: "ClusterRole", "Role", ""
#  toleration:
#  cm:
#    architecture: cm-v1

imageCredentials:
  hooklauncher:
    registry:
      url:
      imagePullPolicy:
    repoPath:
  logshipper:
    registry:
      url:
      imagePullPolicy:
    repoPath:
  helmtest:
    registry:
      url:
      imagePullPolicy:
    repoPath:
  repoPath:
  pullPolicy: IfNotPresent
# pullSecret:
  registry: # Overrides global registry
    url:
    ## Secret must be manually created in the namespace.
    # deprecated, it will be removed
    #pullSecret:
  eric-pm-br-initcontainer:
    repoPath:
  eric-pm-bulk-reporter:
    repoPath:
  eric-pm-alarm-reporter:
    repoPath:
  eric-pm-sftp:
    repoPath:

# DR-470222-010: Local streamingMethod parameter
# choice="indirect, direct, dual"
# indirect - stdout to infrastructure logging framework
# direct - direct streaming to the *Log Aggregator* (Log Transformer)
# dual - stdout to infrastructure logging framework and direct streaming to Log Aggregator 
# null - Default value, the streaming method is determined by global.log.streamingMethod
log:
  streamingMethod:

logShipper:
  logLevel: "info"
  storage:
    size: "1Gi"
    medium: "Ephemeral"
  input:
    files:
      - enabled: true
        paths:
          - "pm-initenv.log"
          - "pm-bulkreporter.log"
          - "pm-sftp.log"
          - "pm-alarmreporter.log"
  output:
    logTransformer:
      host: eric-log-transformer

# AUM service is part of the cluster.
aumSupport:
  enabled: false
  # Name of the AUM service.
  serviceName: eric-sec-admin-user-management
  # Default for authentication failure delay when AUM
  # does not provide the value. Integer.
  authFailureDelayDefault: 3 # in seconds

terminationGracePeriodSeconds: 30
service:
  endpoints:
    pmScrapeTarget:
      tls:
        enforced: required
        verifyClientCertificate: required
  type: LoadBalancer
  servicePort: 9022
  externalIPv4:
    enabled:          # <empty>/true/false
    loadBalancerIP:
    externalTrafficPolicy: Cluster
    servicePort: 9022
    annotations:
      cloudProviderLB: {}  # used in deployments other than ECFE
      sharedVIPLabel:
      addressPoolName:
  externalIPv6:
    enabled:         # <empty>/true/false
    loadBalancerIP:
    externalTrafficPolicy: Cluster
    servicePort: 9022
    annotations:
      cloudProviderLB: {}  # used in deployments other than ECFE
      sharedVIPLabel:
      addressPoolName:
  annotations:
    cloudProviderLB: {}  # used in deployments other than ECFE
    sharedVIPLabel: ""
    addressPoolName: ""
  loadBalancerIP: ""
  externalTrafficPolicy: Cluster
  sshHostKeys:
    name: pm-rop-sftp-server
  pmBulksftpPort:
    dscp: 0
  allocateLoadBalancerNodePorts: false

pmServer:
  pmServiceName: eric-pm-server

env:
  maxHttpSession: 7
  httpTimeout: 10
  alignMeasTypesForMeasObjLDNs: false
  fileLocation: /PerformanceManagementReportFiles
  maxNoOfPmFiles: 1000
  cmhost: eric-cm-mediator:5003
  cmhost_https: eric-cm-mediator:5004
  pmhost: eric-pm-server:9090
  pmhost_https: eric-pm-server:9089
  kmshost: eric-sec-key-management:8200
  swVersion: ""
  iscompressed: false
  logLevel: info
  dnPrefix: ""
  userLabel: ""
  nodeName: ""
  nodeType: ""
  supportedGps: "one-min five-min fifteen-min thirty-min one-hour twelve-hour one-day"
  timeDelay: 0
  objectStorageHost: eric-data-object-storage-mn:9000
  sshdMACSOverride: "-hmac-sha1:hmac-sha2-256:hmac-sha2-512:umac-64@openssh.com:umac-128@openssh.com:hmac-sha1-etm@openssh.com:umac-64-etm@openssh.com"
  sshdKEYALGORITHMSOverride: "-diffie-hellman-group14-sha1:diffie-hellman-group-exchange-sha256:ecdh-sha2-nistp256:ecdh-sha2-nistp384:ecdh-sha2-nistp521:ecdsa-sha2-nistp256"
  sshdHostKeyAlgorithmsOverride: "ssh_host_rsa_key:ssh_host_dsa_key:ssh_host_ecdsa_key:ssh_host_ed25519_key"

thresholdReporter:
  enabled: false
  alarmHandlerHostname: "eric-fh-alarm-handler"
  alarmHandlerPort: 6005
  alarmHandlerTlsPort: 6006
  thresholdGps: "ten-seconds thirty-seconds one-min five-min fifteen-min thirty-min one-hour twelve-hour one-day"
  maxAlarmQueueLength: 500

enhanceQuery:
  enabled: false
  lookbackGP: 1

applicationId:
  enabled: false
  asihHostname: "eric-si-application-sys-info-handler"
  asihPort: 8080
  asihTlsPort: 5000

trace:
  enabled: false
  sampler:
    type: probabilistic
    param: 0.01
    managerHostPort:
    maxOperations: 0
    refreshInterval: 0
  reporter:
    maxQueueSize: 0
    flushInterval: 0
    logSpans: false
  agent:
    host: eric-dst-jg-agent
    port: 6831

yangModelSupport:
  enabled: true
  overlay:
    enabled: false

labels: {}

helmtest:
   enabled: false
   enableDeletePolicy: true

networkPolicy:
  enabled: true

nodeSelector:
  eric-pm-bulk-reporter: {}
  hooklauncher: {}

podDisruptionBudget:
  minAvailable: 0

podPriority:
  eric-pm-bulk-reporter:
    priorityClassName: ""
  hooklauncher:
    priorityClassName: ""
  helmtest:
    priorityClassName: ""

podSecurityContext:
  supplementalGroups: []

persistentVolumeClaim:
  enabled: false
  storageClassName: ""
  storageConnectivity: networked
  existingClaim: ""
  accessMode: ReadWriteOnce
  size: 500Mi
  subPath: ""
  annotations:
    "helm.sh/resource-policy": keep

security:
  tls:
    cmMediator:
      enabled: true
      serviceName: eric-cm-mediator
    pmServer:
      enabled: true
      serviceName: eric-pm-server
      certificateAuthorityBackwardCompatibility: false
    objectStorage:
      enabled: true
      serviceName: eric-data-object-storage-mn
    alarmHandler:
      enabled: true
      serviceName: eric-fh-alarm-handler
    appSysInfoHandler:
      enabled: true
      serviceName: eric-si-application-sys-info-handler
    ldapServer:
      enabled: true
  keyManagement:
    enabled: false
    serviceName: eric-sec-key-management
  certificateManagement:
    enabled: false

## Probes
probes:
  bulkreporter:
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 15
      timeoutSeconds: 15
      failureThreshold: 3
      successThreshold: 1
    livenessProbe:
      initialDelaySeconds: 15
      periodSeconds: 15
      timeoutSeconds: 15
      failureThreshold: 3
      successThreshold: 1
  alarmreporter:
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 15
      timeoutSeconds: 15
      failureThreshold: 3
      successThreshold: 1
    livenessProbe:
      initialDelaySeconds: 15
      periodSeconds: 15
      timeoutSeconds: 15
      failureThreshold: 3
      successThreshold: 1
  pmsftp:
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 15
      timeoutSeconds: 15
      failureThreshold: 3
      successThreshold: 1
    livenessProbe:
      initialDelaySeconds: 15
      periodSeconds: 20
      timeoutSeconds: 15
      failureThreshold: 3
      successThreshold: 1
  logshipper:
    livenessProbe:
      initialDelaySeconds: 1
      periodSeconds: 10
      timeoutSeconds: 10
      failureThreshold: 3
      successThreshold: 1

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  initcontainer:
    requests:
      cpu: "50m"
      memory: "50Mi"
      ephemeral-storage:
    limits:
      cpu: "1"
      memory: "200Mi"
      ephemeral-storage:
  bulkreporter:
    requests:
      cpu: "100m"
      memory: "50Mi"
      ephemeral-storage:
    limits:
      cpu: "1"
      memory: "200Mi"
      ephemeral-storage:
  alarmreporter:
    requests:
      cpu: "100m"
      memory: "50Mi"
      ephemeral-storage:
    limits:
      cpu: "1"
      memory: "200Mi"
      ephemeral-storage:
  pmsftp:
    requests:
      cpu: "50m"
      memory: "50Mi"
      ephemeral-storage:
    limits:
      cpu: "1"
      memory: "200Mi"
      ephemeral-storage:
  logshipper:
    requests:
      memory: "50Mi"
      cpu: "50m"
      ephemeral-storage:
    limits:
      memory: "100Mi"
      cpu: "100m"
      ephemeral-storage:
  hooklauncher:
    requests:
      memory: "50Mi"
      cpu: "20m"
      ephemeral-storage: "100Mi"
    limits:
      memory: "100Mi"
      cpu: "50m"
      ephemeral-storage: "100Mi"
  helmtest:
    requests:
      cpu: 100m
      memory: 128Mi
      ephemeral-storage: 15Mi
    limits:
      cpu: 100m
      memory: 128Mi
      ephemeral-storage: 15Mi

## Authentication/Users Information
# userConfig (mandatory), the user information for the yang-provider service
# The two authentication type can be used independently.
userConfig:
  # Kubernetes Secret based user configuration
  secretName: ""
  secretKey: ""
  # LDAP server configuration
  ldap:
    enabled: true
    useIPv6DNSFirst: false
    uri: "ldap://eric-sec-ldap-server:389"
    ssluri: "ldaps://eric-sec-ldap-server:636"
    searchBase: "ou=people,dc=la,dc=adp,dc=ericsson"
    rolesConfig:
      readOnlyGroup: "SystemReadOnly,ApplicationOperator"
      readWriteGroup: "SystemAdministrator,ApplicationAdministrator"

## ROP File Storage Backend (Alpha Feature)
objectStorage:
  enabled: false
  secretName: eric-data-object-storage-mn-secret

annotations: {}

bandwidth:
  # eric-pm-bulk-reporter:
  #   maxEgressRate: ""
  # This parameter is being deprecated, please use bandwidth.eric-pm-bulk-reporter.maxEgressRate instead
  maxEgressRate: ""

tolerations:
  eric-pm-bulk-reporter:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 0
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 0
  hooklauncher: []

# topologySpreadConstraints:
#   eric-pm-bulk-reporter: []
# This parameter is being deprecated, please use topologySpreadConstraints.eric-pm-bulk-reporter instead
topologySpreadConstraints: []

appArmorProfile:
  type:
  localhostProfile:
  eric-pm-br-initcontainer:
    type:
    localhostProfile:
  eric-pm-bulk-reporter:
    type:
    localhostProfile:
  eric-pm-alarm-reporter:
    type:
    localhostProfile:
  eric-pm-sftp:
    type:
    localhostProfile:
  logshipper:
    type:
    localhostProfile:
  hooklauncher:
    type:
    localhostProfile:

seccompProfile:
  type:

securityPolicy:
  eric-pm-bulk-reporter:
    rolename: "eric-pm-bulk-reporter"
  hooklauncher:
    rolename: "eric-lcm-smart-helm-hooks"
  helmtest:
    rolename: "eric-pm-bulk-reporter-helmtest"
