[unix_http_server]
file=/var/run/supervisor.sock

[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
logfile_backups=0
logfile_maxbytes=0
pidfile=/var/run/supervisord.pid

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:container_cleanup]
command=/sbin/container-cleanup.sh
autostart=true
autorestart=false
redirect_stderr=true
stdout_logfile=/var/log/superv-container-cleanup.log
stdout_logfile_backups=0
startsecs=0
priority=10

[program:rsyslogd]
command=/usr/sbin/rsyslogd -4 -n -f /opt/sftp-k8s/rsyslog.conf
autostart=false
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/superv-rsyslogd.log
stdout_logfile_backups=0
priority=100

[program:execprobe]
command=/usr/bin/execprobe --configuration=/opt/sftp-k8s/execprobe.yaml --containername=eric-pm-sftp --serviceid=eric-pm-bulkreporter --loglevel={{- .Values.env.logLevel }}
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/superv-execprobe.log
stdout_logfile_backups=0
priority=100

[program:logctl]
command=/usr/bin/tail -F -q /var/log/messages /var/log/superv-sssd.log /var/log/superv-taskscheduler.log /var/log/superv-sshd.log /var/log/superv-pamupdate.log /var/log/superv-fsmonitor.log
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stdout_logfile_backups=0
priority=50

[program:alarmfiforeader]
command=/usr/bin/alarmfiforeader -sssd-file=/var/log/sssd.log -supervisord-file=/var/log/supervisord.log
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/superv-sssd.log
stdout_logfile_maxbytes=0
stdout_logfile_backups=0
priority=100

[program:sssd]
command=/usr/sbin/sssd -d {{ template "eric-pm-bulk-reporter.sssdDebugLevel" . }} -i --logger=stderr --debug-microseconds=1 -c /opt/sftp-rw-k8s/sssd.conf
autostart=false
autorestart=true
redirect_stderr=true
stdout_events_enabled=false
stdout_logfile=/var/log/sssd.log
stdout_logfile_maxbytes=0
stdout_logfile_backups=0
priority=300

[program:fsmonitord]
command=/usr/bin/fs_monitor
autostart=false
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/superv-fsmonitor.log
stdout_logfile_backups=0
stdout_logfile_maxbytes=0
priority=300

[program:pamupdated]
command=/usr/bin/pamupdated -d {{ template "eric-pm-bulk-reporter.authFailDelayMountPath" . | quote }}
autostart=false
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/superv-pamupdate.log
stdout_logfile_backups=0
stdout_logfile_maxbytes=0
priority=300

[program:sshd]
environment = LD_PRELOAD="/usr/lib64/libaudit_stub.so"
command=/usr/sbin/sshd -D
autostart=false
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/superv-sshd.log
stdout_logfile_backups=0
stdout_logfile_maxbytes=0
priority=300

[program:crond]
command=/usr/bin/taskscheduler -interval="minutely"
autostart=false
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/superv-taskscheduler.log
stdout_logfile_maxbytes=0
stdout_logfile_backups=0
priority=400

[program:initenv]
command=/initenv
autostart=true
autorestart=false
stdout_syslog=true
stderr_syslog=true
priority=500
