{{- if (eq (include "eric-data-document-database-pg.operator-enabled" .) "true") }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: {{ template "eric-data-document-database-pg.name" . }}-fe
  labels:
    {{- include "eric-data-document-database-pg.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-data-document-database-pg.annotations" . | nindent 4 }}
{{- end }}