{{- if (eq (include "eric-data-document-database-pg.fe-render" .) "true") }}
apiVersion: v1
data:
  replica-pwd: {{ randAlphaNum 12 | nospace | b64enc }}
  replica-user: cmVwbGljYQo=
  metrics-pwd: ZXhwb3J0ZXIK
kind: Secret
metadata:
  name: {{ template "eric-data-document-database-pg.name" . }}-commonuser
type: Opaque
{{- end }}
