{{- if (eq (include "eric-data-document-database-pg.load-legecy-template-enabled" .) "true") }}
{{- $helmHooks := dict -}}
{{- $_ := set $helmHooks "helm.sh/hook" "pre-install,pre-delete,pre-upgrade,pre-rollback" -}}
{{- $_ := set $helmHooks "helm.sh/hook-delete-policy" "before-hook-creation" -}}
{{- $_ := set $helmHooks "helm.sh/hook-weight" "-5" -}}
{{- $commonAnn := fromYaml (include "eric-data-document-database-pg.annotations" .) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "eric-data-document-database-pg.name" . }}-hook
  labels: {{- include "eric-data-document-database-pg.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-data-document-database-pg.mergeAnnotations" (dict "location" .Template.Name "sources" (list $helmHooks $commonAnn)) | trim | nindent 4 }}
rules:
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - roles
  - rolebindings
  verbs:
  - list
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - roles
  - rolebindings
  resourceNames:
  - {{ template "eric-data-document-database-pg.name" . }}
  verbs:
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  # delete is required only for 'patronictl remove'
  - delete
  - deletecollection
- apiGroups:
  - "apps"
  resources:
  - statefulsets
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - "batch"
  resources:
  - jobs
  resourceNames:
  - {{ template "eric-data-document-database-pg.name" . }}-restore-pgdatau
  verbs:
  - get
  - delete
{{- end }}