{{- if (eq (include "eric-data-document-database-pg.load-legecy-template-enabled" .) "true") }}
{{- if .Values.brAgent.enabled  }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "eric-data-document-database-pg.name" . }}-bragent
  labels:
    {{- $labels := dict -}}
    {{- $_ := set $labels "app" (printf "%s-%s" (include "eric-data-document-database-pg.name" .) "bragent") -}}
    {{- $commonLabels := fromYaml (include "eric-data-document-database-pg.labels" .) -}}
    {{- include "eric-data-document-database-pg.mergeLabels" (dict "location" .Template.Name "sources" (list $labels $commonLabels)) | trim | nindent 4 }}
  annotations: {{- include "eric-data-document-database-pg.annotations" . | nindent 4 }}
spec:
  selector:
    app: {{ template "eric-data-document-database-pg.name" . }}-bragent
  ## Remove service type parameter to be exposed comply with DR-D1125-101
  type: ClusterIP
  ports:
  - name: http
    port: 8083 
    targetPort: 8083
  {{- if (eq (include "eric-data-document-database-pg.internalIPFamily" .) "IPv4") }}
  ipFamilies: ["IPv4"]
  {{- else if (eq (include "eric-data-document-database-pg.internalIPFamily" .) "IPv6") }}
  ipFamilies: ["IPv6"]
  {{- end }}
{{- end }}
{{- end }}