{{- if (eq (include "eric-data-document-database-pg.fe-render" .) "true") }}
apiVersion: v1
data:
  super-pwd: {{ randAlphaNum 12 | nospace | b64enc }}
kind: Secret
metadata:
  name: {{ template "eric-data-document-database-pg.name" . }}-superuser
type: Opaque
{{- end }}
