{{- if and .Values.server.ha.enabled .Values.promxy.dynamicDiscovery.enabled -}}
{{- if empty .Values.promxy.serviceAccountName }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "eric-pm-server.promxyName" . }}
  labels: {{- include "eric-pm-server.promxyLabels" . | nindent 4 }}
  {{- if .Values.promxy.extraLabels }}
  {{ toYaml .Values.promxy.extraLabels | nindent 4 }}
  {{- end }}
  annotations: {{ include "eric-pm-server.annotations" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - endpoints
      - pods
      - services
    verbs:
      - get
      - list
      - watch
{{- end }}
{{- end }}
