{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "test-cnf-with-hpa.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "test-cnf-with-hpa.name" . }}
    helm.sh/chart: {{ include "test-cnf-with-hpa.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "test-cnf-with-hpa.fullname" . }}
              port:
                number: 80
{{- end }}

