{{- $helmHooks := dict -}}
{{- $_ := set $helmHooks "helm.sh/hook" "pre-rollback" -}}
{{- $_ := set $helmHooks "helm.sh/hook-delete-policy" "hook-succeeded,before-hook-creation" -}}
{{- $_ := set $helmHooks "helm.sh/hook-weight" "-204" -}}
{{- $commonAnn := fromYaml (include "eric-data-document-database-pg.annotations" .) -}}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: {{ template "eric-data-document-database-pg.name" . }}-prero-cmupdate
  labels: {{- include "eric-data-document-database-pg.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-data-document-database-pg.mergeAnnotations" (dict "location" .Template.Name "sources" (list $helmHooks $commonAnn)) | trim | nindent 4 }}
