{{- if (eq (include "eric-data-document-database-pg.operator-enabled" .) "true") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "eric-data-document-database-pg.beServiceAccountName" . }}
  labels: {{- include "eric-data-document-database-pg.labels" . | nindent 4 }}
  annotations: {{- include "eric-data-document-database-pg.annotations" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "eric-data-document-database-pg.beServiceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "eric-data-document-database-pg.beServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}