{{- if eq (include "etcd.enabled" .) "true" -}}
apiVersion: v1
kind: Secret
metadata:
  name: eric-data-distributed-coordinator-creds
type: Opaque
data:
  etcdpasswd: {{ "adpsecret" | b64enc | quote }}
{{- end -}}