apiVersion: v1
kind: Secret
metadata:
  name: eric-sec-ldap-server-creds
type: Opaque
data:
  adminid: ZmVkZXJhdG9y
  passwd: a2V5Y2xvYWs=
  adminpasswd: JDYkNGlhWDdDTDEkSnhrdzJtTTV1WXRiZm95ZG51RGQ4WkZyTm5UclpOVWtlN2MudzEzUDhPYW5DN092UFNMbHBVQjdHMzhJTDVPWk1FaGxRYm1uT3B0UzR0WHZheHkxUzE=
  adminuser: ZGF5MHVzZXI=
