{{- if (eq (include "eric-data-document-database-pg.load-legecy-template-enabled" .) "true") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "eric-data-document-database-pg.name" . }}
  labels:
    {{- $labels := dict -}}
    {{- $_ := set $labels "app" (include "eric-data-document-database-pg.name" .) -}}
    {{- $_ := set $labels "cluster-name" (include "eric-data-document-database-pg.name" .) -}}
    {{- $commonLabels := fromYaml (include "eric-data-document-database-pg.labels" .) -}}
    {{- include "eric-data-document-database-pg.mergeLabels" (dict "location" .Template.Name "sources" (list $labels $commonLabels)) | trim | nindent 4 }}
  annotations:
    {{- $metricsAnn := dict -}}
    {{- if .Values.metrics.enabled }}
      {{- $_ := set $metricsAnn "prometheus.io/scrape" "true" -}}
      {{- $_ := set $metricsAnn "prometheus.io/port" (.Values.metrics.service.port | toString) -}}
      {{- $_ := set $metricsAnn "prometheus.io/scheme" (ternary "https" "http" (and (not (eq (include "eric-data-document-database-pg.global-security-tls-enabled" .) "false")) (eq .Values.service.endpoints.postgresExporter.tls.enforced "required"))) -}}
    {{- end }}
    {{- $commonAnn := fromYaml (include "eric-data-document-database-pg.annotations" .) -}}
    {{- include "eric-data-document-database-pg.mergeAnnotations" (dict "location" .Template.Name "sources" (list $metricsAnn $commonAnn)) | trim | nindent 4 }}
spec:
  ## Remove service type parameter to be exposed comply with DR-D1125-101
  type: ClusterIP
  ports:
  - name: postgresql
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
{{- if .Values.metrics.enabled }}
  {{- if and (not (eq (include "eric-data-document-database-pg.global-security-tls-enabled" .) "false")) (eq .Values.service.endpoints.postgresExporter.tls.enforced "required") }}
  - name: metrics-tls
  {{- else }}
  - name: metrics
  {{- end }}
    port: {{ .Values.metrics.service.port }}
    targetPort: {{ .Values.metrics.service.port }}
{{- end }}
  {{- if (eq (include "eric-data-document-database-pg.internalIPFamily" .) "IPv4") }}
  ipFamilies: ["IPv4"]
  {{- else if (eq (include "eric-data-document-database-pg.internalIPFamily" .) "IPv6") }}
  ipFamilies: ["IPv6"]
  {{- end }}
{{- end }}