{{- if (eq (include "eric-data-document-database-pg.load-legecy-template-enabled" .) "true") }}
{{- if .Values.brAgent.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ template "eric-data-document-database-pg.name" . }}-bragent-logging
  annotations: {{- include "eric-data-document-database-pg.annotations" . | nindent 4 }}
  labels: {{- include "eric-data-document-database-pg.labels.extended-defaults" . | nindent 4 }}
data:
  log4j2.xml: | 
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration status="info" monitorInterval="5">
        <Appenders>
            <Console name="Console" target="SYSTEM_OUT">
                <PatternLayout>
                    <pattern>
                        {"version": "1.2.0", "timestamp": "%d{yyyy-MM-dd'T'HH:mm:ss.SSSZZZZZ}", "severity": "%p{WARN=warning, DEBUG=debug, ERROR=error, FATAL=critical, TRACE=debug, INFO=info}", "service_id": "eric-data-document-database-pg", "message": "%enc{%m}{JSON}%exception{separator(|)}", "metadata":  {"container_name": {{ printf "%s-bra" (include "eric-data-document-database-pg.name" .) | quote }}}, "extra_data": {"file": "%file", "line": "%line"}}%n
                    </pattern>
                </PatternLayout>
            </Console>
        </Appenders>
        <Loggers>
            <Logger name="com.ericsson.adp.mgmt.pgagent" level="{{ .Values.brAgent.PGAgentLogLevel }}" additivity="false">
                <AppenderRef ref="Console"/>
            </Logger>
            <Root level="{{ .Values.brAgent.RootLogLevel }}">
                <AppenderRef ref="Console"/>
            </Root>
        </Loggers>
    </Configuration>
{{- end }}
{{- end }}
