{{- if (eq (include "eric-data-document-database-pg.load-legecy-template-enabled" .) "true") }}
{{- if .Values.global -}}
{{- if and .Values.global.networkPolicy .Values.networkPolicy -}}
{{- if and .Values.global.networkPolicy.enabled .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "eric-data-document-database-pg.name" . }}-default-allow
  labels: {{- include "eric-data-document-database-pg.labels" . | nindent 4 }}
  annotations: {{- include "eric-data-document-database-pg.annotations" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ template "eric-data-document-database-pg.name" . }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ template "eric-data-document-database-pg.name" . }}
    - podSelector:
        matchLabels:
          app: {{ template "eric-data-document-database-pg.name" . }}-backup-pgdata
    - podSelector:
        matchLabels:
          app: {{ template "eric-data-document-database-pg.name" . }}-restore-pgdata
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ default "eric-pm-server" .Values.metrics.hostname }}
    {{- if (eq (include "eric-data-document-database-pg.operator-enabled" .) "true") }}
    - podSelector:
        matchLabels:
          operator: "eric-data-document-database-pg"
    {{- end }}
{{- include "eric-data-document-database-pg.networkPolicy.matchLabels" . | indent 4 }}
    ports:
    - port: 8008
      protocol: TCP
    - port: 8083
      protocol: TCP
    - port: {{ .Values.service.port }}
      protocol: TCP
{{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.service.port }}
      protocol: TCP
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
