{{- $securityPolicyflags := include "eric-pm-bulk-reporter.securityPolicy" . | fromYaml -}}
{{- $createFlag := get $securityPolicyflags "createFlag" -}}
{{- $oldPolicyFlag := get $securityPolicyflags "oldPolicyFlag" -}}
{{- if (eq "true" $createFlag) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "eric-pm-bulk-reporter.securityPolicy.rolebinding.name" (dict "root" . "oldPolicyFlag" $oldPolicyFlag) }}
  annotations: {{- include "eric-pm-bulk-reporter.roleBinding.annotations" . | nindent 4 }}
  labels: {{- include "eric-pm-bulk-reporter.labels" . | nindent 4 }}
roleRef:
 apiGroup: rbac.authorization.k8s.io
    {{- if (eq "true" $oldPolicyFlag) }}
 kind: ClusterRole
 name: {{ include "eric-pm-bulk-reporter.roleBinding.reference" . }}
    {{- else }}
 kind: {{ include "eric-pm-bulk-reporter.securityPolicy.rolekind" . }}
 name: {{ include "eric-pm-bulk-reporter.securityPolicy.rolename" . }}
    {{- end }}
subjects:
 - kind: ServiceAccount
   name: {{ template "eric-pm-bulk-reporter.name" . }}
{{- end -}}
