apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eric-ctrl-bro.name" . }}-startup
  labels: {{- include "eric-ctrl-bro.labels" . | nindent 4 }}
  annotations: {{- include "eric-ctrl-bro.annotations" . | nindent 4 }}
data:
    RUNBRO: "true"
    SERVICEID: {{ template "eric-ctrl-bro.name" . }}