{{- if (eq (include "eric-data-document-database-pg.operator-enabled" .) "true") }}
{{- $helmHooks := dict -}}
{{- $_ := set $helmHooks "helm.sh/hook" "pre-upgrade,pre-rollback" -}}
{{- $_ := set $helmHooks "helm.sh/hook-delete-policy" "before-hook-creation" -}}
{{- $_ := set $helmHooks "helm.sh/hook-weight" "-5" -}}
{{- $commonAnn := fromYaml (include "eric-data-document-database-pg.annotations" .) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "eric-data-document-database-pg.name" . }}-pgdata-hook-fe
  labels: {{- include "eric-data-document-database-pg.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-data-document-database-pg.mergeAnnotations" (dict "location" .Template.Name "sources" (list $helmHooks $commonAnn)) | nindent 4 }}
rules:
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - roles
  - rolebindings
  verbs:
  - create
  - get
  - list
  - delete
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - roles
  - rolebindings
  resourceNames:
  - {{ template "eric-data-document-database-pg.name" . }}
  verbs:
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - patch
  - update
  - get
  - list
  # delete is required only for 'patronictl remove'
  - delete
  - deletecollection
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - delete
  - deletecollection
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - delete
  - get
  - list
  - delete
  - deletecollection
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - delete
  - deletecollection
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - patch
  - update
  - get
  - list
  - delete
- apiGroups:
  - "apps"
  resources:
  - statefulsets
  - deployments
  verbs:
  - get
  - list
  - update
  - delete
- apiGroups:
  - "batch"
  resources:
  - jobs
  resourceNames:
  - {{ template "eric-data-document-database-pg.name" . }}-restore-pgdatau-op
  verbs:
  - get
  - delete
- apiGroups:
  - "networking.k8s.io"
  resources:
  - networkpolicies
  resourceNames:
  - {{ template "eric-data-document-database-pg.name" . }}-hook-op
  verbs:
  - get
  - delete
# The following rules is for Openshift
- apiGroups:
  - ""
  resources:
  - endpoints/restricted
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - delete
  - deletecollection
- apiGroups:
  - "docdb.data.ericsson.com"
  resources:
  - documentdbs
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - list
  - delete
{{- end }}
