{{- if (eq (include "eric-data-document-database-pg.operator-enabled" .) "true") }}
{{- if eq (include "eric-data-document-database-pg.isOpMigrationRequired" .) "true" -}}
{{- $helmHooks := dict -}}
{{- $_ := set $helmHooks "helm.sh/hook" "post-upgrade" -}}
{{- $_ := set $helmHooks "helm.sh/hook-delete-policy" "before-hook-creation" -}}
{{- $_ := set $helmHooks "helm.sh/hook-weight" "-5" -}}
{{- $commonAnn := fromYaml (include "eric-data-document-database-pg.annotations" .) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "eric-data-document-database-pg.name" . }}-shh-hook
  labels: {{- include "eric-data-document-database-pg.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-data-document-database-pg.mergeAnnotations" (dict "location" .Template.Name "sources" (list $helmHooks $commonAnn)) | trim | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - patch
{{- end }}
{{- end }}
