apiVersion: v1
kind: Service
metadata:
  name: {{ template "pm-testapp.fullname" . }}
  labels:
    app: {{ template "pm-testapp.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    prometheus.io/scheme: 'http'
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app: {{ template "pm-testapp.name" . }}
    release: {{ .Release.Name }}
