apiVersion: v1
kind: Secret
metadata:
  name: eric-sec-access-mgmt-creds
type: Opaque
data:
  {{ index .Values "eric-sec-access-mgmt" "statefulset" "userkey" }}: {{ index .Values "eric-sec-access-mgmt-cred" "keycloak" "username" | b64enc }}
  {{ index .Values "eric-sec-access-mgmt" "statefulset" "passwdkey" }}: {{ index .Values "eric-sec-access-mgmt-cred" "keycloak" "password" | b64enc }}
  {{ index .Values "eric-sec-access-mgmt" "persistence" "dbUserkey" }}: {{ index .Values "eric-sec-access-mgmt-cred" "database" "username" | b64enc }}
  {{ index .Values "eric-sec-access-mgmt" "persistence" "dbPasswdkey" }}: {{ index .Values "eric-sec-access-mgmt-cred" "database" "password" | b64enc }}
