{{- if eq (include "alarm.enabled" .) "true" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: eric-fh-alarm-handler-faultmappings
data:
{{ (.Files.Glob "faultmappings/*").AsConfig | indent 2 }}
{{- end -}}
