{{- if .Values.global -}}
{{- if and .Values.global.networkPolicy .Values.networkPolicy -}}
{{- if and .Values.global.networkPolicy.enabled .Values.networkPolicy.enabled -}}
{{- if .Values.bro.enableConfigurationManagement -}}

{{/*-------------------------------------------------------------------*/}}
{{/*---------------------- CMEIA (MS1) support ------------------------*/}}
{{/*---- Alpha feature for CloudRAN and preparation for CMEIA MS1 -----*/}}
{{/*---- Callbacks arrive from different sources                  -----*/}}
{{/*-------------------------------------------------------------------*/}}
{{- if (include "eric-ctrl-bro.cmeia.active" .) -}}
---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "eric-ctrl-bro.name" . }}-action-allow
  labels:
    {{- include "eric-ctrl-bro.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-ctrl-bro.annotations" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ template "eric-ctrl-bro.name" . }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.service.endpoints.action.actionService }}
    ports:
    - port: {{ .Values.bro.cmmNotifTlsPort }}
      protocol: TCP

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "eric-ctrl-bro.name" . }}-statedata-allow
  labels:
    {{- include "eric-ctrl-bro.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-ctrl-bro.annotations" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ template "eric-ctrl-bro.name" . }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.service.endpoints.statedata.statedataService }}
    ports:
    - port: {{ .Values.bro.cmmNotifTlsPort }}
      protocol: TCP

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "eric-ctrl-bro.name" . }}-validator-allow
  labels:
    {{- include "eric-ctrl-bro.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-ctrl-bro.annotations" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ template "eric-ctrl-bro.name" . }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.service.endpoints.validator.validatorService }}
    ports:
    - port: {{ .Values.bro.cmmNotifTlsPort }}
      protocol: TCP
{{- else }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ template "eric-ctrl-bro.name" . }}-cmm-allow
  labels: {{- include "eric-ctrl-bro.labels" . | nindent 4 }}
  annotations: {{- include "eric-ctrl-bro.annotations" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ template "eric-ctrl-bro.name" . }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.cmm.host }}
    ports:
    - port: {{ .Values.bro.cmmNotifTlsPort }}
      protocol: TCP
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}