{{- if ne ((.Values).shhRbacEnabled | toString ) "false" -}}
{{- $helmHook := dict -}}
{{- $_ := set $helmHook "helm.sh/hook" "pre-upgrade,pre-rollback" -}}
{{- $_ := set $helmHook "helm.sh/hook-delete-policy" "before-hook-creation" -}}
{{- $_ := set $helmHook "helm.sh/hook-weight" "-202" -}}
{{- $commonAnn := fromYaml (include "eric-data-document-database-pg.annotations" .) -}}
{{- $commonLabels := fromYaml (include "eric-data-document-database-pg.labels" .) -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "eric-data-document-database-pg.name" . }}-op-dispatch
  labels:
    {{- $podTempLabels := dict -}}
    {{- $_ := set $podTempLabels "ericsson.com/managed-by" "hooklauncher" -}}
    {{- include "eric-data-document-database-pg.mergeLabels" (dict "location" .Template.Name "sources" (list $podTempLabels $commonLabels)) | trim | nindent 4 }}
  annotations:
    {{- include "eric-data-document-database-pg.mergeAnnotations" (dict "location" .Template.Name "sources" (list $helmHook $commonAnn)) | trim | nindent 4 }}
rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - get
    - list
    - create
    - update
    - patch
    - watch
    # delete is required only for 'patronictl remove'
    - delete
    - deletecollection
  - apiGroups:
    - ""
    resources:
    - services
    - endpoints
    verbs:
    - get
    - patch
    - update
    # the following three privileges are necessary only when using endpoints
    - create
    - list
    - watch
    # delete is required only for for 'patronictl remove'
    - delete
    - deletecollection
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - get
    - list
    - watch
    - patch
    - delete
    - deletecollection
  - apiGroups:
    - ""
    resources:
    - pods/log
    verbs:
    - get
    - list
  - apiGroups:
    - ""
    resources:
    - persistentvolumeclaims
    verbs:
    - list
    - get
    - create
    - update
    - patch
    - delete
    - deletecollection
  - apiGroups:
    - "apps"
    resources:
    - statefulsets
    verbs:
    - get
    - list
    - update
    - patch
    - delete
  - apiGroups:
    - "apps"
    resources:
    - deployments
    verbs:
    - get
    - list
    - watch
    - create
    - patch
    - update
    - delete
    - deletecollection
  - apiGroups:
    - "batch"
    resources:
    - jobs
    verbs:
    - get
    - list
    - create
    - delete
    - deletecollection
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - deletecollection
  - apiGroups:
    - ""
    resources:
    - serviceaccounts
    verbs:
    - get
    - list
    - create
    - patch
    - update
    - delete

  - apiGroups:
    - "rbac.authorization.k8s.io"
    resources:
    - roles
    verbs:
    - create
    - get
    - list
    - patch
    - delete
    - deletecollection

  - apiGroups:
    - "rbac.authorization.k8s.io"
    resources:
    - rolebindings
    verbs:
    - create
    - get
    - list
    - patch
    - delete
    - deletecollection

  - apiGroups:
    - "networking.k8s.io"
    resources:
    - networkpolicies
    verbs:
    - get
    - list
    - create
    - patch
    - update
    - delete
  - apiGroups:
    - policy
    resources:
    - poddisruptionbudgets
    verbs:
    - get
    - list
    - create
    - patch
    - update
    - watch
    - delete
    - deletecollection
  - apiGroups:
    - siptls.sec.ericsson.com
    resources:
    - internalcertificates
    - internalusercas
    verbs:
    - get
    - list
    - create
    - patch
    - delete
  # The following rules is for Openshift
  - apiGroups:
    - ""
    resources:
    - endpoints/restricted
    verbs:
    - get
    - list
    - create
    - patch
    - update
    - delete
    - deletecollection

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "eric-data-document-database-pg.name" . }}-op-dispatch
  labels:
    {{- $podTempLabels := dict -}}
    {{- $_ := set $podTempLabels "ericsson.com/managed-by" "hooklauncher" -}}
    {{- include "eric-data-document-database-pg.mergeLabels" (dict "location" .Template.Name "sources" (list $podTempLabels $commonLabels)) | trim | nindent 4 }}
  annotations:
    {{- include "eric-data-document-database-pg.mergeAnnotations" (dict "location" .Template.Name "sources" (list $helmHook $commonAnn)) | trim | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "eric-data-document-database-pg.name" . }}-op-dispatch
subjects:
  - namespace: {{ .Release.Namespace }}
    kind: ServiceAccount
    name: {{ template "eric-data-document-database-pg.name" . }}-op-dispatch

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "eric-data-document-database-pg.name" . }}-op-dispatch
  labels:
    {{- $podTempLabels := dict -}}
    {{- $_ := set $podTempLabels "ericsson.com/managed-by" "hooklauncher" -}}
    {{- include "eric-data-document-database-pg.mergeLabels" (dict "location" .Template.Name "sources" (list $podTempLabels $commonLabels)) | trim | nindent 4 }}
  annotations:
    {{- include "eric-data-document-database-pg.mergeAnnotations" (dict "location" .Template.Name "sources" (list $helmHook $commonAnn)) | trim | nindent 4 }}

---
{{- $rolekind := (include "eric-data-document-database-pg.securityPolicy.rolekind" .) -}}
{{- if $rolekind }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "eric-data-document-database-pg.name" . }}-op-dispatch-{{ lower (trunc 1 $rolekind) }}-{{ include "eric-data-document-database-pg.securityPolicy.rolename" (dict "Values" .Values "PodName" "dispatchjob") }}-sp
  labels:
    {{- $podTempLabels := dict -}}
    {{- $_ := set $podTempLabels "ericsson.com/managed-by" "hooklauncher" -}}
    {{- include "eric-data-document-database-pg.mergeLabels" (dict "location" .Template.Name "sources" (list $podTempLabels $commonLabels)) | trim | nindent 4 }}
  annotations:
    {{- include "eric-data-document-database-pg.mergeAnnotations" (dict "location" .Template.Name "sources" (list $helmHook $commonAnn)) | trim | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ $rolekind }}
  name: {{ include "eric-data-document-database-pg.securityPolicy.rolename" (dict "Values" .Values "PodName" "dispatchjob") }}
subjects:
- kind: ServiceAccount
  name: {{ template "eric-data-document-database-pg.name" . }}-op-dispatch
{{- else -}}
{{- if .Values.global -}}
  {{- if .Values.global.security -}}
    {{- if .Values.global.security.policyBinding -}}
      {{- if .Values.global.security.policyBinding.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  {{- if .Values.securityContext.allowPrivilegeEscalation }}
  name: {{ template "eric-data-document-database-pg.name" . }}-dispatch-security-policy
  {{- else }}
  name: {{ template "eric-data-document-database-pg.name" . }}-dispatch-secdef-policy
  {{- end }}
  labels:
    {{- $podTempLabels := dict -}}
    {{- $_ := set $podTempLabels "ericsson.com/managed-by" "hooklauncher" -}}
    {{- include "eric-data-document-database-pg.mergeLabels" (dict "location" .Template.Name "sources" (list $podTempLabels $commonLabels)) | trim | nindent 4 }}
  annotations:
    {{- include "eric-data-document-database-pg.mergeAnnotations" (dict "location" .Template.Name "sources" (list $helmHook $commonAnn)) | trim | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  {{- if .Values.securityContext.allowPrivilegeEscalation }}
  name: {{ include "eric-data-document-database-pg.securityPolicy.reference" . }}
  {{- else }}
  name: {{ include "eric-data-document-database-pg.securityPolicy.reference-default" . }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ template "eric-data-document-database-pg.name" . }}-op-dispatch
      {{- end -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
