# Condition determining hpa
{{ if .Values.autoscaling.enabled -}}
  {{- if (semverCompare ">=1.23" .Capabilities.KubeVersion.GitVersion) }}
apiVersion: autoscaling/v2
  {{- else }}
apiVersion: autoscaling/v2beta2
  {{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "test-cnf-with-hpa.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "test-cnf-with-hpa.name" . }}
    helm.sh/chart: {{ include "test-cnf-with-hpa.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  maxReplicas: {{ .Values.maxReplicas }}
  minReplicas: {{ .Values.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "test-cnf-with-hpa.fullname" . }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
{{- end }}
