{{- if (eq (include "eric-data-document-database-pg.load-legecy-template-enabled" .) "true") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "eric-data-document-database-pg.name" . }}-rolebinding
  labels: {{- include "eric-data-document-database-pg.labels" . | nindent 4 }}
  annotations: {{- include "eric-data-document-database-pg.annotations" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "eric-data-document-database-pg.name" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ template "eric-data-document-database-pg.name" . }}-sa
{{- end }}