{{- if (eq (include "eric-data-document-database-pg.operator-enabled" .) "true") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "eric-data-document-database-pg.name" . }}-fe
  labels:
    {{- include "eric-data-document-database-pg.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-data-document-database-pg.annotations" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "eric-data-document-database-pg.name" . }}-fe
subjects:
- kind: ServiceAccount
  name: {{ template "eric-data-document-database-pg.name" . }}-fe
  #namespace: qminzhgfeo
{{- end }}