apiVersion: v1
kind: Secret
data:
  users.yaml: dXNlcnM6CiAgLSB1c2VyOiBhZHB1c2VyCiAgICBncm91cHM6IFtwbS1zZnRwLXVzZXJzXQogICAgZW5jcnlwdGVkUGFzczogJDEkVUYuTm5uVmkkcjVHQmRxbjY5WDh6VTN1OUFEMzVHLwo=
metadata:
  name: {{ index .Values "eric-pm-bulk-reporter" "userConfig" "secretName" }}
type: Opaque
