{{- if .Values.server.ha.enabled -}}
{{- if .Capabilities.APIVersions.Has "policy/v1" }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "eric-pm-server.promxyName" . }}
  labels: {{- include "eric-pm-server.promxyLabels" . | nindent 4 }}
  {{- if .Values.promxy.extraLabels }}
  {{ toYaml .Values.promxy.extraLabels | nindent 4 }}
  {{- end }}
  annotations: {{ include "eric-pm-server.annotations" . | nindent 4 }}
spec:
  minAvailable: {{ int .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app: {{ template "eric-pm-server.promxyName" . }}
{{- end }}
